### ISSUE TITLE
error: identifier "cudaSetupArgument" is undefined

### ISSUE THREAD

**Issue by smhr** [treecode/Bonsai#38] opened 2020-01-08 16:03 UTC
Hi, I want to do my phantomSPH simulations with BonsaiSPH. When I compile BonsaiSPH, I get this error:
```
/home/x1/CODES_REPOS/Bonsai/runtime/include/my_cuda_rt.h(1167): error: identifier "cudaSetupArgument" is undefined

/home/x1/CODES_REPOS/Bonsai/runtime/include/my_cuda_rt.h(1461): error: identifier "cudaConfigureCall" is undefined

/home/x1/CODES_REPOS/Bonsai/runtime/include/my_cuda_rt.h(1474): error: identifier "cudaLaunch" is undefined

3 errors detected in the compilation of "/tmp/tmpxft_000071bf_00000000-6_dev_approximate_gravity_warp_new.cpp1.ii".
CMake Error at bonsai2_slowdust_generated_dev_approximate_gravity_warp_new.cu.o.cmake:268 (message):
  Error generating file
  /home/x1/CODES_REPOS/Bonsai/runtime/CMakeFiles/bonsai2_slowdust.dir/CUDAkernels/./bonsai2_slowdust_generated_dev_approximate_gravity_warp_new.cu.o


CMakeFiles/bonsai2_slowdust.dir/build.make:661: recipe for target 'CMakeFiles/bonsai2_slowdust.dir/CUDAkernels/bonsai2_slowdust_generated_dev_approximate_gravity_warp_new.cu.o' failed
make[2]: *** [CMakeFiles/bonsai2_slowdust.dir/CUDAkernels/bonsai2_slowdust_generated_dev_approximate_gravity_warp_new.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bonsai2_slowdust.dir/all' failed
make[1]: *** [CMakeFiles/bonsai2_slowdust.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
I have installed cuda-10.1 with on a computer with Quadro P4000 GPU.
Is there any step-by-step document for BonsaiSPH? Many thanks

**Comment by jbedorf** [comment] 2020-01-09 08:56
I just pushed a fix for the compilation issues. They were caused by the removal of some functions from the CUDA libraries.

I'm afraid there is no full step-by-step guide, however here are a few pointers:

Before compilation you have to modify some of the SPH integrator properties here:
https://github.com/treecode/Bonsai/blob/BonsaiSPH/runtime/src/main.cpp#L839

The file format that is used can be seen in this tool (which converts an ASCII dump of the Phantom files into our internal format):
https://github.com/treecode/Bonsai/blob/BonsaiSPH/tools/IO/cvt_phantomASCII2bonsai.cpp

After compilation and creating input data you can run the code via:
` ./bonsai2_slowdust -f <inputfile> --usempiio -s 2` 
You can find out all possible arguments by running: `./bonsai2_slowdust -h`

**Comment by smhr** [comment] 2020-01-09 09:31
Many thanks. The previous problem is solved, but now I get:
```
Bonsai/runtime/CUDAkernels/sortKernels.cu:29:11: fatal error: cub/util_allocator.cuh: No such file or directory
  #include <cub/util_allocator.cuh>
           ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at bonsai2_slowdust_generated_sortKernels.cu.o.cmake:219 (message):
  Error generating
  /media/d1/CODES_REPOS/Bonsai/runtime/CMakeFiles/bonsai2_slowdust.dir/CUDAkernels/./bonsai2_slowdust_generated_sortKernels.cu.o
```
I downloaded cub-1.8.0, but how can I use it? I apologize I'm not familiar with cmake.

**Comment by jbedorf** [comment] 2020-01-09 09:35
You would have to place cub in the Bonsai source tree, but an easier way is to not use cub:
Run: 
`ccmake .`
and switch `USE_CUB` from ON to OFF

**Comment by smhr** [comment] 2020-01-09 09:36
Thanks a lot!

**Closed** 2020-01-09 09:38 UTC
